export const VARIABLE_LISTA_PRODUCTO = 'VARIABLE_LISTA_PRODUCTO'
export const VARIABLE_LISTA_PRODUCTO_RECOGE = 'VARIABLE_LISTA_PRODUCTO_RECOGE'
export const PRODUCTS_DOWNLOAD_ERROR = 'PRODUCTS_DOWNLOAD_ERROR'